const canvas=document.querySelector('#habitat'),ctx=canvas.getContext('2d');
const $=s=>document.querySelector(s);let api,frame,w=innerWidth,h=innerHeight,scale=80,origin={x:w*.61,y:h*.51},paused=false,mode=0,debug=false,uneven=false,pointer=null,last=0,lastAnnouncement=-1;
const stones=[[-1.8,-.6,.65],[1.7,.9,.8],[.5,-1.8,.5]];
function resize(){w=innerWidth;h=innerHeight;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);scale=Math.min(w*(w<700?.19:.12),h*.17,112);origin={x:w<700?w*.56:w*.62,y:w<700?h*.54:h*.51};if(api)api.pet_bounds(Math.max(.6,Math.min(origin.x,w-origin.x)/scale-1.15),Math.max(.6,Math.min(origin.y-100,h-origin.y-140)/scale-1.0));}
const project=q=>[origin.x+q[0]*scale,origin.y+(q[1]*.78-q[2]*.7)*scale];
const point=(a,i)=>[a[i],a[i+1],a[i+2]];
function path(points,closed=false){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));if(closed)ctx.closePath();}
function smooth(points){ctx.beginPath();const n=points.length;for(let i=0;i<n;i++){const p=points[i],next=points[(i+1)%n],prev=points[(i+n-1)%n];if(i===0)ctx.moveTo((prev[0]+p[0])/2,(prev[1]+p[1])/2);ctx.quadraticCurveTo(p[0],p[1],(p[0]+next[0])/2,(p[1]+next[1])/2)}ctx.closePath();}
function background(time){ctx.fillStyle='#10191e';ctx.fillRect(0,0,w,h);let g=ctx.createRadialGradient(origin.x,origin.y,0,origin.x,origin.y,Math.max(w,h)*.65);g.addColorStop(0,'#243638');g.addColorStop(.45,'#17272b');g.addColorStop(1,'#0b131b');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);
 ctx.save();ctx.translate(origin.x,origin.y);ctx.scale(1,.78);for(let r=1;r<=4;r++){ctx.beginPath();ctx.arc(0,0,scale*(r+.15),0,Math.PI*2);ctx.strokeStyle=`rgba(151,176,153,${r===2?.09:.035})`;ctx.lineWidth=1;ctx.stroke()}ctx.restore();
 // Deterministic botanical silhouettes and dust are decorative render state.
 for(let i=0;i<100;i++){const x=((i*7919)%1000)/1000*w,y=((i*3217)%1000)/1000*h;ctx.fillStyle=`rgba(187,207,162,${.04+(i%4)*.014})`;ctx.beginPath();ctx.arc(x,y,.5+(i%3)*.3,0,Math.PI*2);ctx.fill()}
 for(const [x,y,flip]of[[w*.96,h*.78,-1],[w*.38,h*.96,1],[w*.98,h*.3,-1]]){ctx.save();ctx.translate(x,y);ctx.rotate(flip*.6);ctx.strokeStyle='#7f927225';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(0,70);ctx.quadraticCurveTo(-20,0,4,-95);ctx.stroke();for(let j=0;j<7;j++){const yy=48-j*20,side=j%2?1:-1;ctx.beginPath();ctx.moveTo(-8,yy);ctx.quadraticCurveTo(side*45,yy-4,side*39,yy-31);ctx.quadraticCurveTo(side*12,yy-32,-8,yy);ctx.fillStyle='#7c937312';ctx.fill();ctx.stroke()}ctx.restore()}
 if(uneven)for(const[x,y,r]of stones){const p=project([x,y,0]);const g=ctx.createRadialGradient(p[0]-r*scale*.25,p[1]-r*scale*.3,2,p[0],p[1],r*scale);g.addColorStop(0,'#4b5b55');g.addColorStop(.7,'#2b3d3b');g.addColorStop(1,'#142326');ctx.fillStyle=g;ctx.beginPath();ctx.ellipse(...p,r*scale,r*scale*.78,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#9db49a18';ctx.stroke()}
}
function draw(){if(!frame)return;const time=frame[1],bodyCount=frame[4],legCount=frame[5],webCount=frame[6];const bodyStart=16,legStart=bodyStart+bodyCount*3,webStart=legStart+legCount*14;const rgb=[frame[8],frame[9],frame[10]].map(v=>Math.round(v*255));const color=`rgb(${rgb.join(',')})`;background(time);
 ctx.lineCap='round';for(let i=0;i<webCount;i++){const a=project(point(frame,webStart+i*6)),b=project(point(frame,webStart+i*6+3));path([a,b]);ctx.strokeStyle=i===webCount-1&&mode===3?'#d1ebcbaa':'#a5c5ba35';ctx.lineWidth=i<98?.85:.55;ctx.stroke();if(i%7===0){ctx.fillStyle='#d8e6c97a';ctx.beginPath();ctx.arc(...a,1.15,0,Math.PI*2);ctx.fill()}}
 const center=project(point(frame,bodyStart+20*3));ctx.save();ctx.translate(center[0],center[1]+scale*.25);ctx.scale(1,.65);let shadow=ctx.createRadialGradient(0,0,4,0,0,scale*.75);shadow.addColorStop(0,'#00000066');shadow.addColorStop(1,'#00000000');ctx.fillStyle=shadow;ctx.beginPath();ctx.arc(0,0,scale*.75,0,Math.PI*2);ctx.fill();ctx.restore();
 // Each leg uses exactly the four joint positions from Rust.
 for(let i=0;i<8;i++){const start=legStart+i*14;const joints=Array.from({length:4},(_,j)=>project(point(frame,start+j*3)));for(let j=0;j<3;j++){path([joints[j],joints[j+1]]);ctx.strokeStyle='#091418';ctx.lineWidth=[8,6,3.6][j]*scale/100;ctx.stroke();ctx.strokeStyle=j===0?'#829c98':j===1?color:'#819f9c';ctx.lineWidth=[5,3.5,1.8][j]*scale/100;ctx.stroke();if(j<2){const t=.7;const a=joints[j],b=joints[j+1];path([[a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t],[a[0]+(b[0]-a[0])*(t+.10),a[1]+(b[1]-a[1])*(t+.10)]]);ctx.strokeStyle='#d2c998';ctx.lineWidth=4*scale/100;ctx.stroke()}}for(let j=1;j<3;j++){ctx.fillStyle='#c1ccab';ctx.beginPath();ctx.arc(...joints[j],2*scale/100,0,Math.PI*2);ctx.fill()}ctx.fillStyle='#c9dfba';ctx.beginPath();ctx.arc(...joints[3],1.5*scale/100,0,Math.PI*2);ctx.fill();if(debug){ctx.strokeStyle=frame[start+12]?'#efb57c':'#93dab3';ctx.lineWidth=1;ctx.beginPath();ctx.arc(...joints[3],6,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#c9dfba';ctx.font='9px monospace';ctx.fillText(`${i+1}`,joints[3][0]+9,joints[3][1])}}
 for(const[start,count,c]of[[8,12,21],[0,8,20]]){const pts=Array.from({length:count},(_,i)=>project(point(frame,bodyStart+(start+i)*3)));const cp=project(point(frame,bodyStart+c*3));const grad=ctx.createRadialGradient(cp[0]-scale*.11,cp[1]-scale*.12,1,cp[0],cp[1],scale*.43);grad.addColorStop(0,color);grad.addColorStop(.55,'#526e76');grad.addColorStop(1,'#192c36');smooth(pts);ctx.fillStyle=grad;ctx.shadowColor='#0008';ctx.shadowBlur=12;ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#b6d1be88';ctx.lineWidth=.8;ctx.stroke();ctx.save();ctx.clip();ctx.translate(...cp);ctx.rotate(frame[2]);if(c===21){ctx.strokeStyle='#e0d5a9';ctx.lineWidth=2.5*scale/100;ctx.beginPath();ctx.moveTo(0,-scale*.23);ctx.bezierCurveTo(-scale*.2,-scale*.04,-scale*.13,scale*.05,0,scale*.23);ctx.bezierCurveTo(scale*.13,scale*.05,scale*.2,-scale*.04,0,-scale*.23);ctx.stroke();ctx.fillStyle='#e7deb1';for(let n=0;n<5;n++){ctx.beginPath();ctx.ellipse(0,(-.13+n*.064)*scale,(n===2?.07:.035)*scale,.018*scale,0,0,Math.PI*2);ctx.fill()}ctx.strokeStyle='#d7cead33';for(let n=0;n<8;n++){const y=(-.2+n*.06)*scale;path([[-.25*scale,y],[.25*scale,y+scale*.05]]);ctx.stroke()}}else{for(const[x,y,r]of[[-.065,-.105,.025],[.065,-.105,.025],[-.13,-.07,.014],[.13,-.07,.014]]){ctx.fillStyle='#09151c';ctx.beginPath();ctx.arc(x*scale,y*scale,r*scale,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f1e9c9';ctx.beginPath();ctx.arc(x*scale-r*scale*.25,y*scale-r*scale*.25,r*scale*.34,0,Math.PI*2);ctx.fill()}}ctx.restore()}
 if(debug){ctx.fillStyle='#f3cd89';for(let i=0;i<bodyCount;i++){const q=project(point(frame,bodyStart+i*3));ctx.beginPath();ctx.arc(...q,2,0,Math.PI*2);ctx.fill()}}
 if(frame[7]>0){ctx.save();ctx.globalAlpha=frame[7];ctx.fillStyle='#e3d6b5';ctx.font='22px Georgia';ctx.fillText('♡',center[0]+scale*.28,center[1]-scale*.5-(1-frame[7])*30);ctx.restore()}
 if(mode===1&&pointer){ctx.strokeStyle='#d1dcb94a';ctx.lineWidth=1;ctx.beginPath();ctx.arc(pointer.x,pointer.y,9,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#c4d8b0';ctx.beginPath();ctx.arc(pointer.x,pointer.y,2,0,Math.PI*2);ctx.fill()}
 if(mode===3){const pct=Math.round(frame[14]*100);if(pct!==lastAnnouncement){$('#activity').textContent=pct===100?'Silk complete':`Weaving · ${pct}%`;lastAnnouncement=pct}}
}
function readFrame(){frame=new Float32Array(api.memory.buffer,api.pet_frame(),api.pet_frame_len());}
function setMode(next){mode=next;api.pet_mode(mode);document.querySelectorAll('[data-mode]').forEach(b=>{const selected=+b.dataset.mode===mode;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',selected)});$('#mood').textContent=['Exploring, at her own pace.','A little curious about you.','Even eight feet need a rest.','Making a place to belong.'][mode];$('#activity').textContent=['Wandering','Following','Resting','Weaving'][mode];lastAnnouncement=-1;}
function environment(){uneven=$('#terrain').checked;api.pet_environment(+$('#curiosity').value,+$('#tension').value,uneven?1:0)}
function locate(event){pointer={x:event.clientX,y:event.clientY};api.pet_target((pointer.x-origin.x)/scale,(pointer.y-origin.y)/(scale*.78));}
canvas.addEventListener('pointermove',e=>{if(api)locate(e)});canvas.addEventListener('pointerdown',e=>{if(!api)return;locate(e);const p=project(point(frame,16+20*3));if(Math.hypot(e.clientX-p[0],e.clientY-p[1])<scale*1.05)api.pet_touch();});
function pause(value){paused=value;$('#pause').textContent=paused?'Resume':'Pause';$('#pause').setAttribute('aria-pressed',paused)}
$('#pause').onclick=()=>pause(!paused);document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>api&&setMode(+b.dataset.mode));['curiosity','tension','terrain'].forEach(id=>$('#'+id).oninput=()=>api&&environment());$('#debug').onchange=e=>debug=e.target.checked;$('#clear').onclick=()=>{if(api){api.pet_clear_web();if(mode===3)setMode(0)}};$('#reset').onclick=()=>{if(api){api.pet_reset();resize();environment();setMode(0);pause(false)}};
addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>last=0);document.addEventListener('keydown',e=>{if(e.target.matches('input,button,summary'))return;if(e.code==='Space'){e.preventDefault();pause(!paused)}if(api&&['1','2','3','4'].includes(e.key))setMode(+e.key-1)});
async function start(){try{const response=await fetch('orb_weaver_pet.wasm');if(!response.ok)throw Error(`Model file: HTTP ${response.status}`);const result=await WebAssembly.instantiate(await response.arrayBuffer(),{});api=result.instance.exports;resize();environment();if(matchMedia('(prefers-reduced-motion: reduce)').matches){setMode(2);pause(true)}readFrame();$('#loading').hidden=true;requestAnimationFrame(loop);}catch(error){$('#loading').textContent='Could not wake Orb. Please run the local launcher and reload.';console.error(error)}}
function loop(now){const dt=last?(now-last)/1000:0;last=now;if(!paused&&!document.hidden)api.pet_update(dt);readFrame();draw();requestAnimationFrame(loop)}resize();background(0);start();
